from enum import Enum


class DealStatus(str, Enum):
    NEGOTIATING = "NEGOTIATING"
    TERMS_LOCKED = "TERMS_LOCKED"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    FUNDED = "FUNDED"
    CREATIVE_DRAFT = "CREATIVE_DRAFT"
    CREATIVE_REVIEW = "CREATIVE_REVIEW"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    POSTED = "POSTED"
    VERIFYING = "VERIFYING"
    RELEASED = "RELEASED"
    REFUNDED = "REFUNDED"
    CANCELED = "CANCELED"


class CreativeStatus(str, Enum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
